version: '3.8'

services:
  web:
    build: .
    command: bundle exec rails s -b '0.0.0.0' -p 3000
    volumes:
      - .:/app
      - ./db:/app/db  # Mount the SQLite database file outside the container
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development